name: Deploy Pages (landing + wiki)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build wiki con MkDocs
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install mkdocs-material
      - run: mkdocs build --strict

      # Prepara cartella di pubblicazione
      - name: Prepare publish dir
        run: |
          rm -rf publish && mkdir -p publish/wiki
          cp -r index.html assets publish/
          cp -r site/* publish/wiki/
          touch publish/.nojekyll

      # Configura e carica artifact Pages
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'publish'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
